// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYdU-1LRb9p6lRAwpJ4Y67bJHxHfI7x0w',
    appId: '1:719015764238:web:c05acded2bddc56e52375f',
    messagingSenderId: '719015764238',
    projectId: 'social-media-app-17404',
    authDomain: 'social-media-app-17404.firebaseapp.com',
    storageBucket: 'social-media-app-17404.appspot.com',
    measurementId: 'G-JDRDYE9YF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMCp__RnCky2sCwy6jti6mqudrqrNIWQ',
    appId: '1:719015764238:android:8749ba80f6d5b70f52375f',
    messagingSenderId: '719015764238',
    projectId: 'social-media-app-17404',
    storageBucket: 'social-media-app-17404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEOIr3V0LGrSF43_zUYxxQZh59zCykL_o',
    appId: '1:719015764238:ios:0ec366589b9436d852375f',
    messagingSenderId: '719015764238',
    projectId: 'social-media-app-17404',
    storageBucket: 'social-media-app-17404.appspot.com',
    iosClientId: '719015764238-ptgvodfn4rdhvrsm56ukrj1r5v3phlc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEOIr3V0LGrSF43_zUYxxQZh59zCykL_o',
    appId: '1:719015764238:ios:d269e4454051f0c652375f',
    messagingSenderId: '719015764238',
    projectId: 'social-media-app-17404',
    storageBucket: 'social-media-app-17404.appspot.com',
    iosClientId: '719015764238-npas2ou64ic3ig8kr74ueceeveemnbhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
